# Haskell CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-11.9
      # specify the version you desire here
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: app_data
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "~/project/server/package.yaml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: database setup
          command: |
            # service postgresql restart
            # sudo -u postgres psql -c "ALTER ROLE postgres WITH PASSWORD 'postgres'; CREATE USER app_data WITH SUPERUSER PASSWORD 'app_data';"
            # sudo -u postgres psql -c "CREATE DATABASE app_data;"
      - run:
          name: build app
          command: |
            pushd server
            stack clean && stack build
            popd
      # run tests!
      - run:
          name: run tests
          command: |
            pushd server
            stack test --no-terminal
            popd
      - save_cache:
          paths:
              - ~/project/server/.stack-work
          key: v1-dependencies-{{ checksum "~/project/server/package.yaml" }}
